### ISSUE TITLE
Command freezes

### ISSUE THREAD

**Issue by icidasset** [jfmengels/elm-review#2] opened 2019-12-01 16:41 UTC
Hi @jfmengels 👋 
Thanks for this great tool!

I seem to be running into an issue where the elm-review command gets "stuck" (or freezes if you will). I've ran the command with `--debug` flag and got this:

```
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Ports.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Reply.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Sources/Processing.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Sources/Processing/Common.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Sources/Processing/Steps.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/Tracks.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/Brain/User/Layer.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Alfred.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Authentication.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Authentication/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Backdrop.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Console.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Css.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Demo.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/DnD.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Equalizer.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Kit.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/List.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Navigation.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Notifications.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Page.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Playlists.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Playlists/Alfred.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Playlists/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Playlists/Directory.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Playlists/Page.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Ports.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Queue.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Queue/Common.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Queue/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Queue/Fill.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Queue/Page.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Reply.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Settings.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Settings/ImportExport.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Settings/Page.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Sources.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Sources/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Sources/Form.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Sources/Page.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Svg/Elements.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Tracks.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Tracks/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Tracks/Reply.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Tracks/Scene.elm
 - /Users/icidasset/Projects/diffuse/src/Applications/UI/Tracks/Scene/List.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Alfred.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Alien.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Chunky.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Chunky/Styled.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Classes.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Color/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Common.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Conditional.elm
 - /Users/icidasset/Projects/diffuse/src/Library/ContextMenu.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Coordinates.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Cryptography/Hmac.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Css/Classes.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Css/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Dict/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Equalizer.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Html/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Icons.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Json/Decode/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/List/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Maybe/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Notifications.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Playlists.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Playlists/Encoding.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Playlists/Matching.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Queue.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Return2.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Return3.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Settings.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Encoding.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Pick.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Processing.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Processing/Encoding.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/AmazonS3.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/AmazonS3/Parser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/AmazonS3/Presign.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Azure/Authorization.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Azure/BlobParser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Azure/FileMarker.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Azure/FileParser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/AzureBlob.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/AzureFile.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Btfs.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Common.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Dropbox.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Dropbox/Parser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Google.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Google/Parser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Ipfs.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Ipfs/Marker.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/Ipfs/Parser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/WebDav.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/WebDav/Marker.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Sources/Services/WebDav/Parser.elm
 - /Users/icidasset/Projects/diffuse/src/Library/String/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Task/Extra.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Time/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Collection.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Collection/Internal.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Collection/Internal/Arrange.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Collection/Internal/Harvest.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Collection/Internal/Identify.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Encoding.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Favourites.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tracks/Sorting.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Tuple/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/Url/Ext.elm
 - /Users/icidasset/Projects/diffuse/src/Library/User/Layer.elm
 - /Users/icidasset/Projects/diffuse/src/Library/User/Layer/Methods/RemoteStorage.elm
```

And then nothing happens after that.
Here's the file it gets stuck on: https://github.com/icidasset/diffuse/blob/4af982288c5e46570f43de1117b07db0a87dfc92/src/Library/User/Layer/Methods/RemoteStorage.elm

Any ideas?
Thanks!

PS. You can try it out for yourself, if you want to, by cloning the project, running `yarn install` and then `make quality`.

**Comment by jfmengels** [comment] 2019-12-01 19:47
Hi @icidasset :)

It doesn't necessarily get stuck at RemoteStorage. `elm-review` prints the list of all files before starting its analysis, and `RemoteStorage.elm` just happens to be  the last one to be shown.

I have tried running it in your project with the following configuration:
```elm
import NoDebug
import NoUnused.CustomTypeConstructors
import NoUnused.Variables
import Review.Rule exposing (Rule)


config : List Rule
config =
    [ NoDebug.rule
    , NoUnused.Variables.rule
    , NoUnused.CustomTypeConstructors.rule
    ]
```

and the program exited correctly.

I would suggest:
- Removing the `elm-stuff` at the root of your project and in the `review/` directory, and trying again.
- If you wrote a custom rule, try and see if you don't have a case of infinite recursion somewhere.

If these don't help, I could take a look and investigate further. If you wrote custom rules, it would be helpful to see them. And whether you have or haven't, a branch with your review configuration would be helpful.

I hope this helps :)

**Comment by icidasset** [comment] 2019-12-01 21:16
Thanks for the quick response!
Few notes:
- I'm using a custom review directory (it's at `system/Review`, it's on the git repo as well)
- I tried removing the `elm-stuff` directory on the root of my project
- There is no `elm-stuff` directory in my review config dir
- No custom rules, just `NoDebug.rule` and `NoUnused.Variables.rule`

**Comment by jfmengels** [comment] 2019-12-01 23:14
> There is no elm-stuff directory in my review config dir

I thought as well, but in the case that there was, it was a good thing to try.

> I tried removing the elm-stuff directory on the root of my project

And it is still not working I presume?

I ran `make quality`, but also `elm-review src/ --config system/Review` like what is done in your makefile,  with a different configuration, and without specifying `src/`, and I have failed to reproduce your issue :s

I run on Linux Ubuntu. Maybe you run on something different, but I am not sure how to investigate further. If you wish to help me investigate, I suggest trying out on a different computer, or simply cloning the repo in a different directory and trying again, maybe that would give a different result :crossed_fingers:

**Comment by icidasset** [comment] 2019-12-02 14:31
> And it is still not working I presume?
Indeed.

> Maybe you run on something different
I'm using macOS 10.14.x

Thanks so much for the help! 😉 
Will try to investigate further.

**Comment by icidasset** [comment] 2019-12-21 17:33
Finally found the problem. I'm generating a giant Elm file (273000 lines in this file) and it freezes while trying to process this file. The reason you didn't have the issue is because that file is only generated when you build the app.

I can't somehow exclude this file, right?
Should've known this was the root of the issue 😅 

Additional info:
- I let the command run for about 10 minutes before giving up (with said large file)
- Works fine without that file 👌

**Comment by jfmengels** [comment] 2020-01-11 10:30
> Finally found the problem. I'm generating a giant Elm file (273000 lines in this file) and it freezes while trying to process this file. The reason you didn't have the issue is because that file is only generated when you build the app.

Ah, that makes a lot of sense. I am working on quite a few things in elm-review, and performance improvements are on my todo list. But if the bulk of the performance hit is because of the Elm parser (which is a library I don't have control over), then I don't know if we'll be able to improve things. If it isn't, then hopefully my performance improvements will improve things.

> I can't somehow exclude this file, right?

Not at the moment, unless it is in a separate directories and you specify you wish to review all the other directories. I suggest you do that if you wish to continue using `elm-review`. Maybe I'll add support for more grain-controlled of files to include/exclude, but I don't know if/how/when that will turn out.

I'll close this in the meantime, but be on the lookout (in several weeks/months, don't hold your breath) for potential performance increases. Hopefully that will make your file (and project) elm-reviewable.

**Closed by jfmengels** 2020-01-11 10:30 UTC

**Comment by jfmengels** [comment] 2020-01-15 09:10
I have done a few tests, and it turns out the analysis which is done in elm-review is actually quite fast, and the slow part is indeed the initial "review project" build (we build an application containing your configuration) but especially the parsing using elm-syntax.

In later versions I'll cache the file parsing result, meaning that everything should go much faster, and once you have parsed your giant file once, it shouldn't be parsed again and that would save time. Until you modify it...

I don't know if that will help you much in practice, but the bottleneck is [elm-syntax](https://github.com/stil4m/elm-syntax/). Maybe your file has some constructs that `elm-syntax` is really not optimizing, or maybe your file is simply too huge for the parse.

I suggest you open an issue over there. I don't know what they can do about it, but your file could serve as a performance "test" for the maintainers to improve the parser's speed.

**Comment by icidasset** [comment] 2020-01-16 13:17
@jfmengels Sounds like the caching might help, couldn't hurt in either case. Thanks for looking into this! Will check out elm-syntax.

**Comment by jfmengels** [comment] 2020-01-16 13:21
I have just added caching yesterday, and `elm-review` is now quite fast!
But the first run stays slow, because we still need to parse all files at least once. The bottleneck here really seems to be `elm-syntax`... :cry: 

Don't expect to release `elm-review` with caching anytime soon, as I am preparing for a major release of the library and the CLI, and that will a lot more time to finish and polish.

**Comment by icidasset** [comment] 2020-01-16 13:23
Awesome, thanks! No worries, take all the time you need ☺️
